### ISSUE TITLE
Todo before manuscript draft

### ISSUE THREAD

**Issue by dyurovsky** [jklafka/language-modeling#2]
- [x] 1. Compute barycenters losses for sizes 1-5
- [x] 2. Use the bend in the knee metric to pick a barycenter size (prob 5 or 6)
- [x] 3. get barycenter loss between global barycenter estimated from hclust and every language's barycenter for unigram and trigrams. Use this to see if there's more variability in unigram curves. Some kind of baseline?
- [x] 4. Try doing this within and across language family
- [ ] 5. make a nice hclust visualization. color languages by family. zoom in on part?
- [x] 6. finish up MI analyses. come to a conclusion 
- [ ] 7.  Study 2 needs to be fleshed out
- [ ] 8. Discussion/Conclusion
- [x] 9. Reproduce Yu et al. plot
- [x] 10. English Wikipedia
- [x] 11. k-fold cross-validation splitting files
- [x] 12. k-fold cross-validation storing models
- [x] 13. k-fold cross-validation storing outputs
- [x] 14. Maurits, Perfors and Navarro (2010) UID deviation metric
- [x] 15. Centering the curves somehow
- [ ] 16. Making the repo approachable
- [ ] 17. If you want to replicate our pipeline, what should you do?
